#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtmultimedia
Version  : 5.15.2
Release  : 30
URL      : https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtmultimedia-everywhere-src-5.15.2.tar.xz
Source0  : https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtmultimedia-everywhere-src-5.15.2.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-3.0
Requires: qtmultimedia-lib = %{version}-%{release}
Requires: qtmultimedia-license = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(Qt5OpenGL)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-app-1.0)
BuildRequires : pkgconfig(gstreamer-audio-1.0)
BuildRequires : pkgconfig(gstreamer-base-1.0)
BuildRequires : pkgconfig(gstreamer-pbutils-1.0)
BuildRequires : pkgconfig(gstreamer-video-1.0)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libpulse-mainloop-glib)
BuildRequires : pkgconfig(openal)
BuildRequires : wayland-dev
Patch1: qtmultimedia-stable-branch.patch

%description
This example performs some simple OpenCL operations on camera or video input
which is assumed to be provided in RGB format. The OpenCL operation is done on
an OpenGL texture using CL-GL interop, without any further readbacks or copies
(except for the initial texture upload, when necessary).

%package dev
Summary: dev components for the qtmultimedia package.
Group: Development
Requires: qtmultimedia-lib = %{version}-%{release}
Provides: qtmultimedia-devel = %{version}-%{release}
Requires: qtmultimedia = %{version}-%{release}

%description dev
dev components for the qtmultimedia package.


%package examples
Summary: examples components for the qtmultimedia package.
Group: Default
Requires: qtmultimedia-dev = %{version}-%{release}

%description examples
examples components for the qtmultimedia package.


%package lib
Summary: lib components for the qtmultimedia package.
Group: Libraries
Requires: qtmultimedia-license = %{version}-%{release}

%description lib
lib components for the qtmultimedia package.


%package license
Summary: license components for the qtmultimedia package.
Group: Default

%description license
license components for the qtmultimedia package.


%prep
%setup -q -n qtmultimedia-everywhere-src-5.15.2
cd %{_builddir}/qtmultimedia-everywhere-src-5.15.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
%qmake QMAKE_CFLAGS+=-fno-lto QMAKE_CXXFLAGS+=-fno-lto
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1652677956
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qtmultimedia
cp %{_builddir}/qtmultimedia-everywhere-src-5.15.2/LICENSE.FDL %{buildroot}/usr/share/package-licenses/qtmultimedia/61907422fefcd2313a9b570c31d203a6dbebd333
cp %{_builddir}/qtmultimedia-everywhere-src-5.15.2/LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/qtmultimedia/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/qtmultimedia-everywhere-src-5.15.2/LICENSE.GPL3 %{buildroot}/usr/share/package-licenses/qtmultimedia/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/qtmultimedia-everywhere-src-5.15.2/LICENSE.GPL3-EXCEPT %{buildroot}/usr/share/package-licenses/qtmultimedia/e93757aefa405f2c9a8a55e780ae9c39542dfc3a
cp %{_builddir}/qtmultimedia-everywhere-src-5.15.2/LICENSE.LGPL3 %{buildroot}/usr/share/package-licenses/qtmultimedia/f45ee1c765646813b442ca58de72e20a64a7ddba
cp %{_builddir}/qtmultimedia-everywhere-src-5.15.2/examples/multimedia/spectrum/3rdparty/fftreal/license.txt %{buildroot}/usr/share/package-licenses/qtmultimedia/2a9842312685da1c09bd4f9cd48d7f1a61b7e6b5
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qabstractvideobuffer_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qaudiobuffer_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qaudiodevicefactory_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qaudiohelpers_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qaudiosystempluginext_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qcamera_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qimagevideobuffer_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediacontrol_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmedianetworkplaylistprovider_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaobject_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaopenglhelper_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaplaylist_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaplaylistcontrol_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaplaylistioplugin_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaplaylistnavigator_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaplaylistprovider_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaplaylistsourcecontrol_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediapluginloader_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediarecorder_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaresourcepolicy_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaresourcepolicyplugin_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaresourceset_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaservice_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediaserviceprovider_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmediastoragelocation_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmemoryvideobuffer_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qmultimediautils_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qplaylistfileparser_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qsamplecache_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qsoundeffect_pulse_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qsoundeffect_qaudio_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qtmultimedia-config_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qtmultimediaglobal_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qvideoframeconversionhelper_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qvideooutputorientationhandler_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qvideosurfaceoutput_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qvideosurfaces_p.h
/usr/include/qt5/QtMultimedia/5.15.2/QtMultimedia/private/qwavedecoder_p.h
/usr/include/qt5/QtMultimedia/QAbstractAudioDeviceInfo
/usr/include/qt5/QtMultimedia/QAbstractAudioInput
/usr/include/qt5/QtMultimedia/QAbstractAudioOutput
/usr/include/qt5/QtMultimedia/QAbstractPlanarVideoBuffer
/usr/include/qt5/QtMultimedia/QAbstractVideoBuffer
/usr/include/qt5/QtMultimedia/QAbstractVideoFilter
/usr/include/qt5/QtMultimedia/QAbstractVideoSurface
/usr/include/qt5/QtMultimedia/QAudio
/usr/include/qt5/QtMultimedia/QAudioBuffer
/usr/include/qt5/QtMultimedia/QAudioDecoder
/usr/include/qt5/QtMultimedia/QAudioDecoderControl
/usr/include/qt5/QtMultimedia/QAudioDeviceInfo
/usr/include/qt5/QtMultimedia/QAudioEncoderSettings
/usr/include/qt5/QtMultimedia/QAudioEncoderSettingsControl
/usr/include/qt5/QtMultimedia/QAudioFormat
/usr/include/qt5/QtMultimedia/QAudioInput
/usr/include/qt5/QtMultimedia/QAudioInputSelectorControl
/usr/include/qt5/QtMultimedia/QAudioOutput
/usr/include/qt5/QtMultimedia/QAudioOutputSelectorControl
/usr/include/qt5/QtMultimedia/QAudioProbe
/usr/include/qt5/QtMultimedia/QAudioRecorder
/usr/include/qt5/QtMultimedia/QAudioRoleControl
/usr/include/qt5/QtMultimedia/QAudioSystemFactoryInterface
/usr/include/qt5/QtMultimedia/QAudioSystemPlugin
/usr/include/qt5/QtMultimedia/QCamera
/usr/include/qt5/QtMultimedia/QCameraCaptureBufferFormatControl
/usr/include/qt5/QtMultimedia/QCameraCaptureDestinationControl
/usr/include/qt5/QtMultimedia/QCameraControl
/usr/include/qt5/QtMultimedia/QCameraExposure
/usr/include/qt5/QtMultimedia/QCameraExposureControl
/usr/include/qt5/QtMultimedia/QCameraFeedbackControl
/usr/include/qt5/QtMultimedia/QCameraFlashControl
/usr/include/qt5/QtMultimedia/QCameraFocus
/usr/include/qt5/QtMultimedia/QCameraFocusControl
/usr/include/qt5/QtMultimedia/QCameraFocusZone
/usr/include/qt5/QtMultimedia/QCameraFocusZoneList
/usr/include/qt5/QtMultimedia/QCameraImageCapture
/usr/include/qt5/QtMultimedia/QCameraImageCaptureControl
/usr/include/qt5/QtMultimedia/QCameraImageProcessing
/usr/include/qt5/QtMultimedia/QCameraImageProcessingControl
/usr/include/qt5/QtMultimedia/QCameraInfo
/usr/include/qt5/QtMultimedia/QCameraInfoControl
/usr/include/qt5/QtMultimedia/QCameraLocksControl
/usr/include/qt5/QtMultimedia/QCameraViewfinderSettings
/usr/include/qt5/QtMultimedia/QCameraViewfinderSettingsControl
/usr/include/qt5/QtMultimedia/QCameraViewfinderSettingsControl2
/usr/include/qt5/QtMultimedia/QCameraZoomControl
/usr/include/qt5/QtMultimedia/QCustomAudioRoleControl
/usr/include/qt5/QtMultimedia/QImageEncoderControl
/usr/include/qt5/QtMultimedia/QImageEncoderSettings
/usr/include/qt5/QtMultimedia/QMediaAudioProbeControl
/usr/include/qt5/QtMultimedia/QMediaAvailabilityControl
/usr/include/qt5/QtMultimedia/QMediaBindableInterface
/usr/include/qt5/QtMultimedia/QMediaContainerControl
/usr/include/qt5/QtMultimedia/QMediaContent
/usr/include/qt5/QtMultimedia/QMediaControl
/usr/include/qt5/QtMultimedia/QMediaGaplessPlaybackControl
/usr/include/qt5/QtMultimedia/QMediaMetaData
/usr/include/qt5/QtMultimedia/QMediaNetworkAccessControl
/usr/include/qt5/QtMultimedia/QMediaObject
/usr/include/qt5/QtMultimedia/QMediaPlayer
/usr/include/qt5/QtMultimedia/QMediaPlayerControl
/usr/include/qt5/QtMultimedia/QMediaPlaylist
/usr/include/qt5/QtMultimedia/QMediaRecorder
/usr/include/qt5/QtMultimedia/QMediaRecorderControl
/usr/include/qt5/QtMultimedia/QMediaResource
/usr/include/qt5/QtMultimedia/QMediaResourceList
/usr/include/qt5/QtMultimedia/QMediaService
/usr/include/qt5/QtMultimedia/QMediaServiceCameraInfoInterface
/usr/include/qt5/QtMultimedia/QMediaServiceDefaultDeviceInterface
/usr/include/qt5/QtMultimedia/QMediaServiceFeaturesInterface
/usr/include/qt5/QtMultimedia/QMediaServiceProviderFactoryInterface
/usr/include/qt5/QtMultimedia/QMediaServiceProviderHint
/usr/include/qt5/QtMultimedia/QMediaServiceProviderPlugin
/usr/include/qt5/QtMultimedia/QMediaServiceSupportedDevicesInterface
/usr/include/qt5/QtMultimedia/QMediaServiceSupportedFormatsInterface
/usr/include/qt5/QtMultimedia/QMediaStreamsControl
/usr/include/qt5/QtMultimedia/QMediaTimeInterval
/usr/include/qt5/QtMultimedia/QMediaTimeRange
/usr/include/qt5/QtMultimedia/QMediaVideoProbeControl
/usr/include/qt5/QtMultimedia/QMetaDataReaderControl
/usr/include/qt5/QtMultimedia/QMetaDataWriterControl
/usr/include/qt5/QtMultimedia/QMultimedia
/usr/include/qt5/QtMultimedia/QRadioData
/usr/include/qt5/QtMultimedia/QRadioDataControl
/usr/include/qt5/QtMultimedia/QRadioTuner
/usr/include/qt5/QtMultimedia/QRadioTunerControl
/usr/include/qt5/QtMultimedia/QSound
/usr/include/qt5/QtMultimedia/QSoundEffect
/usr/include/qt5/QtMultimedia/QVideoDeviceSelectorControl
/usr/include/qt5/QtMultimedia/QVideoEncoderSettings
/usr/include/qt5/QtMultimedia/QVideoEncoderSettingsControl
/usr/include/qt5/QtMultimedia/QVideoFilterRunnable
/usr/include/qt5/QtMultimedia/QVideoFrame
/usr/include/qt5/QtMultimedia/QVideoProbe
/usr/include/qt5/QtMultimedia/QVideoRendererControl
/usr/include/qt5/QtMultimedia/QVideoSurfaceFormat
/usr/include/qt5/QtMultimedia/QVideoWindowControl
/usr/include/qt5/QtMultimedia/QtMultimedia
/usr/include/qt5/QtMultimedia/QtMultimediaDepends
/usr/include/qt5/QtMultimedia/QtMultimediaVersion
/usr/include/qt5/QtMultimedia/qabstractvideobuffer.h
/usr/include/qt5/QtMultimedia/qabstractvideofilter.h
/usr/include/qt5/QtMultimedia/qabstractvideosurface.h
/usr/include/qt5/QtMultimedia/qaudio.h
/usr/include/qt5/QtMultimedia/qaudiobuffer.h
/usr/include/qt5/QtMultimedia/qaudiodecoder.h
/usr/include/qt5/QtMultimedia/qaudiodecodercontrol.h
/usr/include/qt5/QtMultimedia/qaudiodeviceinfo.h
/usr/include/qt5/QtMultimedia/qaudioencodersettingscontrol.h
/usr/include/qt5/QtMultimedia/qaudioformat.h
/usr/include/qt5/QtMultimedia/qaudioinput.h
/usr/include/qt5/QtMultimedia/qaudioinputselectorcontrol.h
/usr/include/qt5/QtMultimedia/qaudiooutput.h
/usr/include/qt5/QtMultimedia/qaudiooutputselectorcontrol.h
/usr/include/qt5/QtMultimedia/qaudioprobe.h
/usr/include/qt5/QtMultimedia/qaudiorecorder.h
/usr/include/qt5/QtMultimedia/qaudiorolecontrol.h
/usr/include/qt5/QtMultimedia/qaudiosystem.h
/usr/include/qt5/QtMultimedia/qaudiosystemplugin.h
/usr/include/qt5/QtMultimedia/qcamera.h
/usr/include/qt5/QtMultimedia/qcameracapturebufferformatcontrol.h
/usr/include/qt5/QtMultimedia/qcameracapturedestinationcontrol.h
/usr/include/qt5/QtMultimedia/qcameracontrol.h
/usr/include/qt5/QtMultimedia/qcameraexposure.h
/usr/include/qt5/QtMultimedia/qcameraexposurecontrol.h
/usr/include/qt5/QtMultimedia/qcamerafeedbackcontrol.h
/usr/include/qt5/QtMultimedia/qcameraflashcontrol.h
/usr/include/qt5/QtMultimedia/qcamerafocus.h
/usr/include/qt5/QtMultimedia/qcamerafocuscontrol.h
/usr/include/qt5/QtMultimedia/qcameraimagecapture.h
/usr/include/qt5/QtMultimedia/qcameraimagecapturecontrol.h
/usr/include/qt5/QtMultimedia/qcameraimageprocessing.h
/usr/include/qt5/QtMultimedia/qcameraimageprocessingcontrol.h
/usr/include/qt5/QtMultimedia/qcamerainfo.h
/usr/include/qt5/QtMultimedia/qcamerainfocontrol.h
/usr/include/qt5/QtMultimedia/qcameralockscontrol.h
/usr/include/qt5/QtMultimedia/qcameraviewfindersettings.h
/usr/include/qt5/QtMultimedia/qcameraviewfindersettingscontrol.h
/usr/include/qt5/QtMultimedia/qcamerazoomcontrol.h
/usr/include/qt5/QtMultimedia/qcustomaudiorolecontrol.h
/usr/include/qt5/QtMultimedia/qimageencodercontrol.h
/usr/include/qt5/QtMultimedia/qmediaaudioprobecontrol.h
/usr/include/qt5/QtMultimedia/qmediaavailabilitycontrol.h
/usr/include/qt5/QtMultimedia/qmediabindableinterface.h
/usr/include/qt5/QtMultimedia/qmediacontainercontrol.h
/usr/include/qt5/QtMultimedia/qmediacontent.h
/usr/include/qt5/QtMultimedia/qmediacontrol.h
/usr/include/qt5/QtMultimedia/qmediaencodersettings.h
/usr/include/qt5/QtMultimedia/qmediaenumdebug.h
/usr/include/qt5/QtMultimedia/qmediagaplessplaybackcontrol.h
/usr/include/qt5/QtMultimedia/qmediametadata.h
/usr/include/qt5/QtMultimedia/qmedianetworkaccesscontrol.h
/usr/include/qt5/QtMultimedia/qmediaobject.h
/usr/include/qt5/QtMultimedia/qmediaplayer.h
/usr/include/qt5/QtMultimedia/qmediaplayercontrol.h
/usr/include/qt5/QtMultimedia/qmediaplaylist.h
/usr/include/qt5/QtMultimedia/qmediarecorder.h
/usr/include/qt5/QtMultimedia/qmediarecordercontrol.h
/usr/include/qt5/QtMultimedia/qmediaresource.h
/usr/include/qt5/QtMultimedia/qmediaservice.h
/usr/include/qt5/QtMultimedia/qmediaserviceproviderplugin.h
/usr/include/qt5/QtMultimedia/qmediastreamscontrol.h
/usr/include/qt5/QtMultimedia/qmediatimerange.h
/usr/include/qt5/QtMultimedia/qmediavideoprobecontrol.h
/usr/include/qt5/QtMultimedia/qmetadatareadercontrol.h
/usr/include/qt5/QtMultimedia/qmetadatawritercontrol.h
/usr/include/qt5/QtMultimedia/qmultimedia.h
/usr/include/qt5/QtMultimedia/qradiodata.h
/usr/include/qt5/QtMultimedia/qradiodatacontrol.h
/usr/include/qt5/QtMultimedia/qradiotuner.h
/usr/include/qt5/QtMultimedia/qradiotunercontrol.h
/usr/include/qt5/QtMultimedia/qsound.h
/usr/include/qt5/QtMultimedia/qsoundeffect.h
/usr/include/qt5/QtMultimedia/qtmultimedia-config.h
/usr/include/qt5/QtMultimedia/qtmultimediadefs.h
/usr/include/qt5/QtMultimedia/qtmultimediaglobal.h
/usr/include/qt5/QtMultimedia/qtmultimediaversion.h
/usr/include/qt5/QtMultimedia/qvideodeviceselectorcontrol.h
/usr/include/qt5/QtMultimedia/qvideoencodersettingscontrol.h
/usr/include/qt5/QtMultimedia/qvideoframe.h
/usr/include/qt5/QtMultimedia/qvideoprobe.h
/usr/include/qt5/QtMultimedia/qvideorenderercontrol.h
/usr/include/qt5/QtMultimedia/qvideosurfaceformat.h
/usr/include/qt5/QtMultimedia/qvideowindowcontrol.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/gstvideoconnector_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstappsrc_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstbufferpoolinterface_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstcodecsinfo_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreameraudioinputselector_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreameraudioprobecontrol_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreamerbufferprobe_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreamerbushelper_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreamermessage_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreamerplayercontrol_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreamerplayersession_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreamervideoinputdevicecontrol_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreamervideooverlay_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreamervideoprobecontrol_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreamervideorenderer_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreamervideorendererinterface_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreamervideowidget_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstreamervideowindow_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgsttools_global_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstutils_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstvideobuffer_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstvideorendererplugin_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qgstvideorenderersink_p.h
/usr/include/qt5/QtMultimediaGstTools/5.15.2/QtMultimediaGstTools/private/qvideosurfacegstsink_p.h
/usr/include/qt5/QtMultimediaGstTools/QtMultimediaGstTools
/usr/include/qt5/QtMultimediaGstTools/QtMultimediaGstToolsDepends
/usr/include/qt5/QtMultimediaGstTools/QtMultimediaGstToolsVersion
/usr/include/qt5/QtMultimediaGstTools/qtmultimediagsttoolsversion.h
/usr/include/qt5/QtMultimediaQuick/5.15.2/QtMultimediaQuick/private/qdeclarativevideooutput_backend_p.h
/usr/include/qt5/QtMultimediaQuick/5.15.2/QtMultimediaQuick/private/qdeclarativevideooutput_p.h
/usr/include/qt5/QtMultimediaQuick/5.15.2/QtMultimediaQuick/private/qdeclarativevideooutput_render_p.h
/usr/include/qt5/QtMultimediaQuick/5.15.2/QtMultimediaQuick/private/qdeclarativevideooutput_window_p.h
/usr/include/qt5/QtMultimediaQuick/5.15.2/QtMultimediaQuick/private/qsgvideonode_p.h
/usr/include/qt5/QtMultimediaQuick/5.15.2/QtMultimediaQuick/private/qsgvideonode_rgb_p.h
/usr/include/qt5/QtMultimediaQuick/5.15.2/QtMultimediaQuick/private/qsgvideonode_texture_p.h
/usr/include/qt5/QtMultimediaQuick/5.15.2/QtMultimediaQuick/private/qsgvideonode_yuv_p.h
/usr/include/qt5/QtMultimediaQuick/5.15.2/QtMultimediaQuick/private/qtmultimediaquickdefs_p.h
/usr/include/qt5/QtMultimediaQuick/QtMultimediaQuick
/usr/include/qt5/QtMultimediaQuick/QtMultimediaQuickDepends
/usr/include/qt5/QtMultimediaQuick/QtMultimediaQuickVersion
/usr/include/qt5/QtMultimediaQuick/qtmultimediaquickversion.h
/usr/include/qt5/QtMultimediaWidgets/5.15.2/QtMultimediaWidgets/private/qpaintervideosurface_p.h
/usr/include/qt5/QtMultimediaWidgets/5.15.2/QtMultimediaWidgets/private/qvideowidget_p.h
/usr/include/qt5/QtMultimediaWidgets/QCameraViewfinder
/usr/include/qt5/QtMultimediaWidgets/QGraphicsVideoItem
/usr/include/qt5/QtMultimediaWidgets/QVideoWidget
/usr/include/qt5/QtMultimediaWidgets/QVideoWidgetControl
/usr/include/qt5/QtMultimediaWidgets/QtMultimediaWidgets
/usr/include/qt5/QtMultimediaWidgets/QtMultimediaWidgetsDepends
/usr/include/qt5/QtMultimediaWidgets/QtMultimediaWidgetsVersion
/usr/include/qt5/QtMultimediaWidgets/qcameraviewfinder.h
/usr/include/qt5/QtMultimediaWidgets/qgraphicsvideoitem.h
/usr/include/qt5/QtMultimediaWidgets/qtmultimediawidgetdefs.h
/usr/include/qt5/QtMultimediaWidgets/qtmultimediawidgetsversion.h
/usr/include/qt5/QtMultimediaWidgets/qvideowidget.h
/usr/include/qt5/QtMultimediaWidgets/qvideowidgetcontrol.h
/usr/lib64/cmake/Qt5Multimedia/Qt5MultimediaConfig.cmake
/usr/lib64/cmake/Qt5Multimedia/Qt5MultimediaConfigVersion.cmake
/usr/lib64/cmake/Qt5Multimedia/Qt5Multimedia_CameraBinServicePlugin.cmake
/usr/lib64/cmake/Qt5Multimedia/Qt5Multimedia_QAlsaPlugin.cmake
/usr/lib64/cmake/Qt5Multimedia/Qt5Multimedia_QGstreamerAudioDecoderServicePlugin.cmake
/usr/lib64/cmake/Qt5Multimedia/Qt5Multimedia_QGstreamerCaptureServicePlugin.cmake
/usr/lib64/cmake/Qt5Multimedia/Qt5Multimedia_QGstreamerPlayerServicePlugin.cmake
/usr/lib64/cmake/Qt5Multimedia/Qt5Multimedia_QM3uPlaylistPlugin.cmake
/usr/lib64/cmake/Qt5Multimedia/Qt5Multimedia_QPulseAudioPlugin.cmake
/usr/lib64/cmake/Qt5MultimediaGstTools/Qt5MultimediaGstToolsConfig.cmake
/usr/lib64/cmake/Qt5MultimediaGstTools/Qt5MultimediaGstToolsConfigVersion.cmake
/usr/lib64/cmake/Qt5MultimediaQuick/Qt5MultimediaQuickConfig.cmake
/usr/lib64/cmake/Qt5MultimediaQuick/Qt5MultimediaQuickConfigVersion.cmake
/usr/lib64/cmake/Qt5MultimediaWidgets/Qt5MultimediaWidgetsConfig.cmake
/usr/lib64/cmake/Qt5MultimediaWidgets/Qt5MultimediaWidgetsConfigVersion.cmake
/usr/lib64/libQt5Multimedia.prl
/usr/lib64/libQt5Multimedia.so
/usr/lib64/libQt5MultimediaGstTools.prl
/usr/lib64/libQt5MultimediaGstTools.so
/usr/lib64/libQt5MultimediaQuick.prl
/usr/lib64/libQt5MultimediaQuick.so
/usr/lib64/libQt5MultimediaWidgets.prl
/usr/lib64/libQt5MultimediaWidgets.so
/usr/lib64/pkgconfig/Qt5Multimedia.pc
/usr/lib64/pkgconfig/Qt5MultimediaWidgets.pc
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri

%files examples
%defattr(-,root,root,-)
/usr/share/qt5/examples/multimedia/audiodecoder/audiodecoder.cpp
/usr/share/qt5/examples/multimedia/audiodecoder/audiodecoder.h
/usr/share/qt5/examples/multimedia/audiodecoder/audiodecoder.pro
/usr/share/qt5/examples/multimedia/audiodecoder/main.cpp
/usr/share/qt5/examples/multimedia/audiodecoder/wavefilewriter.cpp
/usr/share/qt5/examples/multimedia/audiodecoder/wavefilewriter.h
/usr/share/qt5/examples/multimedia/audiodevices/audiodevices.cpp
/usr/share/qt5/examples/multimedia/audiodevices/audiodevices.h
/usr/share/qt5/examples/multimedia/audiodevices/audiodevices.pro
/usr/share/qt5/examples/multimedia/audiodevices/audiodevicesbase.ui
/usr/share/qt5/examples/multimedia/audiodevices/main.cpp
/usr/share/qt5/examples/multimedia/audioengine/audioengine.pro
/usr/share/qt5/examples/multimedia/audioengine/qml/audioengine.qml
/usr/share/qt5/examples/multimedia/audioengine/qml/audioengine.qmlproject
/usr/share/qt5/examples/multimedia/audioengine/qml/content/MyAudioEngine.qml
/usr/share/qt5/examples/multimedia/audioengine/qml/content/engine-loop.wav
/usr/share/qt5/examples/multimedia/audioengine/qml/content/horn.wav
/usr/share/qt5/examples/multimedia/audioengine/qml/content/whistle.wav
/usr/share/qt5/examples/multimedia/audioinput/audioinput.cpp
/usr/share/qt5/examples/multimedia/audioinput/audioinput.h
/usr/share/qt5/examples/multimedia/audioinput/audioinput.pro
/usr/share/qt5/examples/multimedia/audioinput/main.cpp
/usr/share/qt5/examples/multimedia/audiooutput/audiooutput.cpp
/usr/share/qt5/examples/multimedia/audiooutput/audiooutput.h
/usr/share/qt5/examples/multimedia/audiooutput/audiooutput.pro
/usr/share/qt5/examples/multimedia/audiooutput/main.cpp
/usr/share/qt5/examples/multimedia/audiorecorder/audiolevel.cpp
/usr/share/qt5/examples/multimedia/audiorecorder/audiolevel.h
/usr/share/qt5/examples/multimedia/audiorecorder/audiorecorder.cpp
/usr/share/qt5/examples/multimedia/audiorecorder/audiorecorder.h
/usr/share/qt5/examples/multimedia/audiorecorder/audiorecorder.pro
/usr/share/qt5/examples/multimedia/audiorecorder/audiorecorder.ui
/usr/share/qt5/examples/multimedia/audiorecorder/main.cpp
/usr/share/qt5/examples/multimedia/declarative-camera/CameraButton.qml
/usr/share/qt5/examples/multimedia/declarative-camera/CameraListButton.qml
/usr/share/qt5/examples/multimedia/declarative-camera/CameraListPopup.qml
/usr/share/qt5/examples/multimedia/declarative-camera/CameraPropertyButton.qml
/usr/share/qt5/examples/multimedia/declarative-camera/CameraPropertyPopup.qml
/usr/share/qt5/examples/multimedia/declarative-camera/FocusButton.qml
/usr/share/qt5/examples/multimedia/declarative-camera/PhotoCaptureControls.qml
/usr/share/qt5/examples/multimedia/declarative-camera/PhotoPreview.qml
/usr/share/qt5/examples/multimedia/declarative-camera/Popup.qml
/usr/share/qt5/examples/multimedia/declarative-camera/VideoCaptureControls.qml
/usr/share/qt5/examples/multimedia/declarative-camera/VideoPreview.qml
/usr/share/qt5/examples/multimedia/declarative-camera/ZoomControl.qml
/usr/share/qt5/examples/multimedia/declarative-camera/declarative-camera.pro
/usr/share/qt5/examples/multimedia/declarative-camera/declarative-camera.qml
/usr/share/qt5/examples/multimedia/declarative-camera/declarative-camera.qmlproject
/usr/share/qt5/examples/multimedia/declarative-camera/declarative-camera.qrc
/usr/share/qt5/examples/multimedia/declarative-camera/images/camera_auto_mode.png
/usr/share/qt5/examples/multimedia/declarative-camera/images/camera_camera_setting.png
/usr/share/qt5/examples/multimedia/declarative-camera/images/camera_flash_auto.png
/usr/share/qt5/examples/multimedia/declarative-camera/images/camera_flash_fill.png
/usr/share/qt5/examples/multimedia/declarative-camera/images/camera_flash_off.png
/usr/share/qt5/examples/multimedia/declarative-camera/images/camera_flash_redeye.png
/usr/share/qt5/examples/multimedia/declarative-camera/images/camera_white_balance_cloudy.png
/usr/share/qt5/examples/multimedia/declarative-camera/images/camera_white_balance_flourescent.png
/usr/share/qt5/examples/multimedia/declarative-camera/images/camera_white_balance_incandescent.png
/usr/share/qt5/examples/multimedia/declarative-camera/images/camera_white_balance_sunny.png
/usr/share/qt5/examples/multimedia/declarative-camera/images/toolbutton.png
/usr/share/qt5/examples/multimedia/declarative-camera/images/toolbutton.sci
/usr/share/qt5/examples/multimedia/declarative-camera/qmlcamera.cpp
/usr/share/qt5/examples/multimedia/declarative-radio/Button.qml
/usr/share/qt5/examples/multimedia/declarative-radio/declarative-radio.pro
/usr/share/qt5/examples/multimedia/declarative-radio/declarative-radio.qrc
/usr/share/qt5/examples/multimedia/declarative-radio/main.cpp
/usr/share/qt5/examples/multimedia/declarative-radio/view.qml
/usr/share/qt5/examples/multimedia/multimedia.pro
/usr/share/qt5/examples/multimedia/radio/main.cpp
/usr/share/qt5/examples/multimedia/radio/radio.cpp
/usr/share/qt5/examples/multimedia/radio/radio.h
/usr/share/qt5/examples/multimedia/radio/radio.pro
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/Array.h
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/Array.hpp
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/DynArray.h
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/DynArray.hpp
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/FFTRealFixLen.h
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/FFTRealFixLen.hpp
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/FFTRealFixLenParam.h
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/FFTRealPassDirect.h
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/FFTRealPassDirect.hpp
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/FFTRealPassInverse.h
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/FFTRealPassInverse.hpp
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/FFTRealSelect.h
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/FFTRealSelect.hpp
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/FFTRealUseTrigo.h
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/FFTRealUseTrigo.hpp
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/OscSinCos.h
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/OscSinCos.hpp
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/def.h
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/fftreal.pro
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/fftreal_wrapper.cpp
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/fftreal_wrapper.h
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/license.txt
/usr/share/qt5/examples/multimedia/spectrum/3rdparty/fftreal/readme.txt
/usr/share/qt5/examples/multimedia/spectrum/README.txt
/usr/share/qt5/examples/multimedia/spectrum/TODO.txt
/usr/share/qt5/examples/multimedia/spectrum/app/app.pro
/usr/share/qt5/examples/multimedia/spectrum/app/engine.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/engine.h
/usr/share/qt5/examples/multimedia/spectrum/app/frequencyspectrum.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/frequencyspectrum.h
/usr/share/qt5/examples/multimedia/spectrum/app/images/record.png
/usr/share/qt5/examples/multimedia/spectrum/app/images/settings.png
/usr/share/qt5/examples/multimedia/spectrum/app/levelmeter.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/levelmeter.h
/usr/share/qt5/examples/multimedia/spectrum/app/main.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/mainwidget.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/mainwidget.h
/usr/share/qt5/examples/multimedia/spectrum/app/progressbar.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/progressbar.h
/usr/share/qt5/examples/multimedia/spectrum/app/settingsdialog.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/settingsdialog.h
/usr/share/qt5/examples/multimedia/spectrum/app/spectrograph.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/spectrograph.h
/usr/share/qt5/examples/multimedia/spectrum/app/spectrum.h
/usr/share/qt5/examples/multimedia/spectrum/app/spectrum.qrc
/usr/share/qt5/examples/multimedia/spectrum/app/spectrumanalyser.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/spectrumanalyser.h
/usr/share/qt5/examples/multimedia/spectrum/app/tonegenerator.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/tonegenerator.h
/usr/share/qt5/examples/multimedia/spectrum/app/tonegeneratordialog.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/tonegeneratordialog.h
/usr/share/qt5/examples/multimedia/spectrum/app/utils.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/utils.h
/usr/share/qt5/examples/multimedia/spectrum/app/waveform.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/waveform.h
/usr/share/qt5/examples/multimedia/spectrum/app/wavfile.cpp
/usr/share/qt5/examples/multimedia/spectrum/app/wavfile.h
/usr/share/qt5/examples/multimedia/spectrum/spectrum.pri
/usr/share/qt5/examples/multimedia/spectrum/spectrum.pro
/usr/share/qt5/examples/multimedia/video/qmlvideo/images/folder.png
/usr/share/qt5/examples/multimedia/video/qmlvideo/images/leaves.jpg
/usr/share/qt5/examples/multimedia/video/qmlvideo/images/up.png
/usr/share/qt5/examples/multimedia/video/qmlvideo/main.cpp
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/Button.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/CameraBasic.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/CameraDrag.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/CameraDummy.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/CameraFullScreen.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/CameraFullScreenInverted.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/CameraItem.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/CameraMove.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/CameraOverlay.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/CameraResize.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/CameraRotate.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/CameraSpin.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/Content.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/ErrorDialog.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/FileBrowser.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/Scene.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/SceneBasic.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/SceneDrag.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/SceneFullScreen.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/SceneFullScreenInverted.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/SceneMove.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/SceneMulti.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/SceneOverlay.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/SceneResize.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/SceneRotate.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/SceneSelectionPanel.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/SceneSpin.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/SeekControl.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoBasic.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoDrag.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoDummy.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoFillMode.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoFullScreen.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoFullScreenInverted.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoItem.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoMetadata.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoMove.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoOverlay.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoPlaybackRate.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoResize.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoRotate.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoSeek.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/VideoSpin.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qml/qmlvideo/main.qml
/usr/share/qt5/examples/multimedia/video/qmlvideo/qmlvideo.png
/usr/share/qt5/examples/multimedia/video/qmlvideo/qmlvideo.pro
/usr/share/qt5/examples/multimedia/video/qmlvideo/qmlvideo.qrc
/usr/share/qt5/examples/multimedia/video/qmlvideo/qmlvideo.svg
/usr/share/qt5/examples/multimedia/video/qmlvideo/trace.h
/usr/share/qt5/examples/multimedia/video/qmlvideofilter_opencl/README
/usr/share/qt5/examples/multimedia/video/qmlvideofilter_opencl/main.cpp
/usr/share/qt5/examples/multimedia/video/qmlvideofilter_opencl/main.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofilter_opencl/qmlvideofilter_opencl.pro
/usr/share/qt5/examples/multimedia/video/qmlvideofilter_opencl/qmlvideofilter_opencl.qrc
/usr/share/qt5/examples/multimedia/video/qmlvideofilter_opencl/rgbframehelper.h
/usr/share/qt5/examples/multimedia/video/qmlvideofx/Info.plist
/usr/share/qt5/examples/multimedia/video/qmlvideofx/filereader.cpp
/usr/share/qt5/examples/multimedia/video/qmlvideofx/filereader.h
/usr/share/qt5/examples/multimedia/video/qmlvideofx/images/Dropdown_arrows.png
/usr/share/qt5/examples/multimedia/video/qmlvideofx/images/Slider_bar.png
/usr/share/qt5/examples/multimedia/video/qmlvideofx/images/Slider_handle.png
/usr/share/qt5/examples/multimedia/video/qmlvideofx/images/Triangle_Top.png
/usr/share/qt5/examples/multimedia/video/qmlvideofx/images/Triangle_bottom.png
/usr/share/qt5/examples/multimedia/video/qmlvideofx/images/icon_BackArrow.png
/usr/share/qt5/examples/multimedia/video/qmlvideofx/images/icon_Folder.png
/usr/share/qt5/examples/multimedia/video/qmlvideofx/images/icon_Menu.png
/usr/share/qt5/examples/multimedia/video/qmlvideofx/images/qt-logo.png
/usr/share/qt5/examples/multimedia/video/qmlvideofx/main.cpp
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/Button.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/Content.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/ContentCamera.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/ContentImage.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/ContentVideo.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/Curtain.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/Divider.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/Effect.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectBillboard.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectBlackAndWhite.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectEmboss.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectGaussianBlur.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectGlow.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectIsolate.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectMagnify.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectPageCurl.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectPassThrough.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectPixelate.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectPosterize.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectRipple.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectSelectionList.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectSepia.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectSharpen.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectShockwave.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectSobelEdgeDetection1.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectTiltShift.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectToon.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectVignette.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectWarhol.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/EffectWobble.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/FileBrowser.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/FileOpen.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/HintedMouseArea.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/Main.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/ParameterPanel.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qml/qmlvideofx/Slider.qml
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qmlvideofx.png
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qmlvideofx.pro
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qmlvideofx.qrc
/usr/share/qt5/examples/multimedia/video/qmlvideofx/qmlvideofx.svg
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/billboard.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/blackandwhite.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/emboss.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/gaussianblur_h.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/gaussianblur_v.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/glow.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/isolate.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/magnify.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/pagecurl.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/pixelate.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/posterize.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/ripple.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/selectionpanel.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/sepia.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/sharpen.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/shockwave.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/sobeledgedetection1.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/tiltshift.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/toon.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/vignette.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/warhol.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/shaders/wobble.fsh
/usr/share/qt5/examples/multimedia/video/qmlvideofx/trace.h
/usr/share/qt5/examples/multimedia/video/snippets/frequencymonitor/frequencymonitor.cpp
/usr/share/qt5/examples/multimedia/video/snippets/frequencymonitor/frequencymonitor.h
/usr/share/qt5/examples/multimedia/video/snippets/frequencymonitor/frequencymonitor.pri
/usr/share/qt5/examples/multimedia/video/snippets/frequencymonitor/frequencymonitordeclarative.cpp
/usr/share/qt5/examples/multimedia/video/snippets/frequencymonitor/frequencymonitordeclarative.pri
/usr/share/qt5/examples/multimedia/video/snippets/frequencymonitor/frequencymonitordeclarative.qrc
/usr/share/qt5/examples/multimedia/video/snippets/frequencymonitor/qml/frequencymonitor/FrequencyItem.qml
/usr/share/qt5/examples/multimedia/video/snippets/performancemonitor/performancemonitor.cpp
/usr/share/qt5/examples/multimedia/video/snippets/performancemonitor/performancemonitor.h
/usr/share/qt5/examples/multimedia/video/snippets/performancemonitor/performancemonitor.pri
/usr/share/qt5/examples/multimedia/video/snippets/performancemonitor/performancemonitordeclarative.cpp
/usr/share/qt5/examples/multimedia/video/snippets/performancemonitor/performancemonitordeclarative.h
/usr/share/qt5/examples/multimedia/video/snippets/performancemonitor/performancemonitordeclarative.pri
/usr/share/qt5/examples/multimedia/video/snippets/performancemonitor/performancemonitordeclarative.qrc
/usr/share/qt5/examples/multimedia/video/snippets/performancemonitor/qml/performancemonitor/PerformanceItem.qml
/usr/share/qt5/examples/multimedia/video/video.pro
/usr/share/qt5/examples/multimediawidgets/camera/camera.cpp
/usr/share/qt5/examples/multimediawidgets/camera/camera.h
/usr/share/qt5/examples/multimediawidgets/camera/camera.pro
/usr/share/qt5/examples/multimediawidgets/camera/camera.qrc
/usr/share/qt5/examples/multimediawidgets/camera/camera.ui
/usr/share/qt5/examples/multimediawidgets/camera/images/shutter.svg
/usr/share/qt5/examples/multimediawidgets/camera/imagesettings.cpp
/usr/share/qt5/examples/multimediawidgets/camera/imagesettings.h
/usr/share/qt5/examples/multimediawidgets/camera/imagesettings.ui
/usr/share/qt5/examples/multimediawidgets/camera/main.cpp
/usr/share/qt5/examples/multimediawidgets/camera/videosettings.cpp
/usr/share/qt5/examples/multimediawidgets/camera/videosettings.h
/usr/share/qt5/examples/multimediawidgets/camera/videosettings.ui
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideoitem/customvideoitem.pro
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideoitem/main.cpp
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideoitem/videoitem.cpp
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideoitem/videoitem.h
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideoitem/videoplayer.cpp
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideoitem/videoplayer.h
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideosurface.pro
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideowidget/customvideowidget.pro
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideowidget/main.cpp
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideowidget/videoplayer.cpp
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideowidget/videoplayer.h
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideowidget/videowidget.cpp
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideowidget/videowidget.h
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideowidget/videowidgetsurface.cpp
/usr/share/qt5/examples/multimediawidgets/customvideosurface/customvideowidget/videowidgetsurface.h
/usr/share/qt5/examples/multimediawidgets/multimediawidgets.pro
/usr/share/qt5/examples/multimediawidgets/player/histogramwidget.cpp
/usr/share/qt5/examples/multimediawidgets/player/histogramwidget.h
/usr/share/qt5/examples/multimediawidgets/player/main.cpp
/usr/share/qt5/examples/multimediawidgets/player/player.cpp
/usr/share/qt5/examples/multimediawidgets/player/player.h
/usr/share/qt5/examples/multimediawidgets/player/player.pro
/usr/share/qt5/examples/multimediawidgets/player/playercontrols.cpp
/usr/share/qt5/examples/multimediawidgets/player/playercontrols.h
/usr/share/qt5/examples/multimediawidgets/player/playlistmodel.cpp
/usr/share/qt5/examples/multimediawidgets/player/playlistmodel.h
/usr/share/qt5/examples/multimediawidgets/player/videowidget.cpp
/usr/share/qt5/examples/multimediawidgets/player/videowidget.h
/usr/share/qt5/examples/multimediawidgets/videographicsitem/main.cpp
/usr/share/qt5/examples/multimediawidgets/videographicsitem/videographicsitem.pro
/usr/share/qt5/examples/multimediawidgets/videographicsitem/videoplayer.cpp
/usr/share/qt5/examples/multimediawidgets/videographicsitem/videoplayer.h
/usr/share/qt5/examples/multimediawidgets/videowidget/main.cpp
/usr/share/qt5/examples/multimediawidgets/videowidget/videoplayer.cpp
/usr/share/qt5/examples/multimediawidgets/videowidget/videoplayer.h
/usr/share/qt5/examples/multimediawidgets/videowidget/videowidget.pro

%files lib
%defattr(-,root,root,-)
/usr/lib64/libQt5Multimedia.so.5
/usr/lib64/libQt5Multimedia.so.5.15
/usr/lib64/libQt5Multimedia.so.5.15.2
/usr/lib64/libQt5MultimediaGstTools.so.5
/usr/lib64/libQt5MultimediaGstTools.so.5.15
/usr/lib64/libQt5MultimediaGstTools.so.5.15.2
/usr/lib64/libQt5MultimediaQuick.so.5
/usr/lib64/libQt5MultimediaQuick.so.5.15
/usr/lib64/libQt5MultimediaQuick.so.5.15.2
/usr/lib64/libQt5MultimediaWidgets.so.5
/usr/lib64/libQt5MultimediaWidgets.so.5.15
/usr/lib64/libQt5MultimediaWidgets.so.5.15.2
/usr/lib64/qt5/plugins/audio/libqtaudio_alsa.so
/usr/lib64/qt5/plugins/audio/libqtmedia_pulse.so
/usr/lib64/qt5/plugins/mediaservice/libgstaudiodecoder.so
/usr/lib64/qt5/plugins/mediaservice/libgstcamerabin.so
/usr/lib64/qt5/plugins/mediaservice/libgstmediacapture.so
/usr/lib64/qt5/plugins/mediaservice/libgstmediaplayer.so
/usr/lib64/qt5/plugins/playlistformats/libqtmultimedia_m3u.so
/usr/lib64/qt5/qml/QtAudioEngine/libdeclarative_audioengine.so
/usr/lib64/qt5/qml/QtAudioEngine/plugins.qmltypes
/usr/lib64/qt5/qml/QtAudioEngine/qmldir
/usr/lib64/qt5/qml/QtMultimedia/Video.qml
/usr/lib64/qt5/qml/QtMultimedia/libdeclarative_multimedia.so
/usr/lib64/qt5/qml/QtMultimedia/plugins.qmltypes
/usr/lib64/qt5/qml/QtMultimedia/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qtmultimedia/2a9842312685da1c09bd4f9cd48d7f1a61b7e6b5
/usr/share/package-licenses/qtmultimedia/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/qtmultimedia/61907422fefcd2313a9b570c31d203a6dbebd333
/usr/share/package-licenses/qtmultimedia/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/qtmultimedia/e93757aefa405f2c9a8a55e780ae9c39542dfc3a
/usr/share/package-licenses/qtmultimedia/f45ee1c765646813b442ca58de72e20a64a7ddba
